// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Proyecto.Data;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618123000_UpdateAdminPasswordHashes")]
    partial class UpdateAdminPasswordHashes
    {
    }
}
